blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://github.com/Jammingway/SFPLiberate/blob/main/docs/
    about: Check the docs before creating an issue
  - name: Discussions
    url: https://github.com/Jammingway/SFPLiberate/discussions
    about: For questions and general discussions
